# Creating an array in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array((1,2,3,4), dtype = 'float16')

In [3]:
arr


array([1., 2., 3., 4.], dtype=float16)

In [4]:
arr = np.array([1,2,3,4], dtype = 'complex')

In [5]:
arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [6]:
# to fetch only the imaginary part then we can use the imag attribute
arr.imag

array([0., 0., 0., 0.])

In [7]:
# to fetch only the real part then we can use real atrribute
arr.real

array([1., 2., 3., 4.])

In [8]:
# if you want to change the real part then 
arr.real = np.array([4,5,6,7])

In [9]:
arr


array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [10]:
# array creating with boolean values then
arr = np.array([1,2,4,0,2,0],dtype = 'bool')
arr

array([ True,  True,  True, False,  True, False])

In [14]:
# creating an array with zeroes with 4 dimension
arr = np.zeros((2,2,3,5))

In [15]:
arr

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [16]:
arr.ndim

4

In [17]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr = np.zeros((2,4,9))
arr

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [19]:
arr.ndim

3

In [20]:
 arr.shape

(2, 4, 9)

In [21]:
# creating an array with one
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr =np.ones((2,3),dtype = 'int16')
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [23]:
# np.empty(): Create an uninitialized array.
arr = np.empty((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# np.full(): Create an array filled with a specified value.
arr = np.full((2,4),99,dtype = 'int64')
arr

array([[99, 99, 99, 99],
       [99, 99, 99, 99]], dtype=int64)

In [28]:
#np.full_like is a NumPy function that creates a new array with the same shape and data type as a given array, filled with a specified valu
a = np.array([[1,2,3,4],[5,6,7,8]])
arr = np.full_like(a,101)
arr

array([[101, 101, 101, 101],
       [101, 101, 101, 101]])

In [17]:
arr = np.zeros_like(a)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
 # using random module genarating random numbers
np.random.rand(3,4)


array([[0.26863038, 0.74801952, 0.438882  , 0.22510667],
       [0.64294325, 0.69782303, 0.92939789, 0.83276904],
       [0.51184351, 0.6221696 , 0.47292619, 0.21944441]])

In [32]:
# using random module with random integer variable(-3,7) indicates from which number to which number and (3,4) indicates the shape
a1= np.random.randint(-3,88,(3,4,3,4))
a1.ndim

4

In [6]:
#np.random.randn(): Generate random numbers from a normal distribution.
random_numbers = np.random.randn(6)
random_numbers

array([ 0.3156679 , -0.72342478,  1.53064115,  1.126847  , -1.67193172,
       -1.36959917])

In [7]:
# creating a identity matrix 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# range function from python like that it will work the parameters are like in the range function
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [19]:
#np.linspace(): Create an array with evenly spaced values over a specified interval.
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [11]:
# loading the data from a text file and that's within the same directory
marks = np.loadtxt('marks.txt',dtype ='str')
marks

array([['mark1', 'mark2'],
       ['42', '43'],
       ['94', '63'],
       ['33', '11']], dtype='<U5')

In [57]:
#skip row is used to skip the rows
marks = np.loadtxt('marks.txt',skiprows =1, dtype='int64')
marks

array([[42, 43],
       [94, 63],
       [33, 11]], dtype=int64)

In [62]:
# to get column vise data then we use upack,  The unpack parameter controls whether the returned array is transposed (i.e., unpacked) or not.:
mark1 , mark2 = np.loadtxt('marks.txt',skiprows=1, dtype ='int64' ,unpack = True)
print(mark1)
print(mark2)

[42 94 33]
[43 63 11]


In [63]:
# save function used to save the files/ arrays in the format of .npy
np.save('sample',np.array([1,2,3,4]))


In [64]:
np.load('sample.npy')

array([1, 2, 3, 4])

In [36]:
# creating a  array using functions and here we can give the shape of the array

np.fromfunction(lambda i,j : i+ j,(3,3),dtype='int64')

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]], dtype=int64)

In [75]:
existing_arr = np.zeros((2,4))
existing_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
# this is using existing array 
existing_arr = np.ones((2,4))
np.fromfunction(lambda i,j : i+j, existing_arr.shape, dtype='int64')

array([[0, 1, 2, 3],
       [1, 2, 3, 4]], dtype=int64)

In [82]:
import numpy as np

# Custom function to calculate values based on row and column indices
def custom_func(i, j):
    return (i + 1) * (j + 1)

# Create a 3x3 matrix using np.fromfunction with the custom function
custom_matrix = np.fromfunction(custom_func, (3, 3), dtype=int)

print("Custom Matrix:")
print(custom_matrix)


Custom Matrix:
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [83]:
identity_matrix = np.fromfunction(lambda i, j: i == j, (5, 5), dtype=int)

print("Identity Matrix:")
print(identity_matrix)

Identity Matrix:
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [ ]:
#np.array(): Create an array from a Python list or tuple.
#np.zeros(): Create an array filled with zeros.
#np.ones(): Create an array filled with ones.
#np.empty(): Create an uninitialized array.
#np.full(): Create an array filled with a specified value.
#np.arange(): Create an array with evenly spaced values within a range.
#np.linspace(): Create an array with evenly spaced values over a specified interval.
#np.eye(): Create a 2-D array with ones on the diagonal and zeros elsewhere.

In [42]:
arr8 = np.random.randint(1,10,size =30).reshape(5,3,2)

In [43]:
arr8.ndim

3

In [45]:
arr8

array([[[3, 5],
        [7, 6],
        [4, 4]],

       [[8, 6],
        [9, 2],
        [6, 7]],

       [[4, 3],
        [9, 1],
        [1, 1]],

       [[8, 6],
        [7, 6],
        [8, 7]],

       [[1, 6],
        [9, 8],
        [6, 5]]])