# indexing and slicing 

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr[-1]

5

In [5]:
arr[0]

1

In [6]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[0,4]

5

In [7]:
 arr[0]

array([1, 2, 3, 4, 5])

In [8]:
# indexing using in  3D array
arr= np.random.randint(-3,10,(2,3,4))
arr

array([[[ 0, -2,  5,  2],
        [ 4, -1, -3, -2],
        [ 6, -2, -3,  3]],

       [[ 6,  2,  5,  3],
        [ 3,  3,  7,  8],
        [ 8,  1,  0,  8]]])

In [9]:
 arr[0,2,2]

-3

In [9]:
arr[0,1,2]

-1

In [10]:
arr[1,2,3]

8

In [11]:
arr[1,1]

array([3, 3, 7, 8])

In [12]:
arr[0,0,3]

2

In [13]:
arr = np.arange(0,20,2)

In [14]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arr[:1]

array([0])

In [16]:
arr[:4]

array([0, 2, 4, 6])

In [17]:
# difference btw slicing in list and nparray
li = [1,2,3,4,5,6,7,8,9]


In [18]:
li_slice = li[0:5]
li_slice

[1, 2, 3, 4, 5]

In [19]:
arr = np.arange(1,10)
arr_slice = arr[0:4]

In [20]:
arr_slice

array([1, 2, 3, 4])

In [21]:
li_slice[0] = 99
li_slice

[99, 2, 3, 4, 5]

In [22]:
print(li,'\n',li_slice)

[1, 2, 3, 4, 5, 6, 7, 8, 9] 
 [99, 2, 3, 4, 5]


In [23]:
#in nparray the both sliced list and the orginal list also get updated but in the case of list in python it will create another memory for the sliced list 
arr_slice[0] = 2032
print(arr_slice,'\n',arr)

[2032    2    3    4] 
 [2032    2    3    4    5    6    7    8    9]


In [31]:
#slicing in multidimensional array
arr = np.array([[1,2,3,4,5],[64,75,82,4,77],[54,88,1,23,44]])
arr[:, 1]

array([ 2, 75, 88])

In [25]:
arr[1:2,1:5] 

array([[75, 82,  4, 77]])

In [26]:
arr[2:3,1:5]

array([[88,  1, 23, 44]])

In [27]:
arr[2,:4:2] #start:end:step_size

array([54,  1])

In [28]:
arr[2,1:4:1]

array([88,  1, 23])

In [29]:
arr[1,4:5]

array([77])

In [30]:
arr

array([[ 1,  2,  3,  4,  5],
       [64, 75, 82,  4, 77],
       [54, 88,  1, 23, 44]])

In [31]:
 #indexing using array:
arr = np.array([
    [1, 2, 3, 4, 5],
    [64, 75, 82, 4, np.nan],
    [54, 88, 1, 23, 44]
])

# Selecting the third row (index 2)
row_index = 2
selected_row = arr[row_index]
print(selected_row)

# Selecting specific columns (e.g., columns at indices 1, 3, and 4)
column_indices = np.array([1, 3, 4])
sliced_array = selected_row[column_indices]

print(sliced_array)  # Output: [88, 23, 44]

[54. 88.  1. 23. 44.]
[88. 23. 44.]


In [32]:
arr= np.array([1,5,35,23,66,3,773,6])
a = arr<55
arr[a]

array([ 1,  5, 35, 23,  3,  6])