In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
arr.shape
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
arr.shape

(2, 5)

In [8]:
arr.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [9]:
# repeat an array 
arr = np.array([1,2,3,4,5,6])
np.repeat(arr,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [10]:
  arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]],
                   [[9, 10], [11, 12]]])
arr_3d.shape

(3, 2, 2)

In [11]:
np.repeat(arr_3d,3,axis =1)


array([[[ 1,  2],
        [ 1,  2],
        [ 1,  2],
        [ 3,  4],
        [ 3,  4],
        [ 3,  4]],

       [[ 5,  6],
        [ 5,  6],
        [ 5,  6],
        [ 7,  8],
        [ 7,  8],
        [ 7,  8]],

       [[ 9, 10],
        [ 9, 10],
        [ 9, 10],
        [11, 12],
        [11, 12],
        [11, 12]]])

In [12]:
#how to implement vertical stack 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.vstack([arr1,arr2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.vstack([arr2,arr2,arr1,arr1])

In [ ]:
arr3 = np.array([[1,2,3,4],[1,2,3,4]])
np.vstack([arr1,arr3,arr2,arr3])

In [18]:
#how to implement vertical stack 
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.hstack([arr])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr1= np.array([[9,10,11,12],[5,2,5,1]])

In [21]:
np.hstack([arr1,arr])

array([[ 9, 10, 11, 12,  1,  2,  3,  4],
       [ 5,  2,  5,  1,  5,  6,  7,  8]])

In [17]:
#expanding and squeezing a array, squeezing is elminate the Removes axes of length 1 from the shape of the array.
#Useful for removing unnecessary dimensions. and if you want to specifcly remove any axis then we can give that using axis = that particular axis
arr = np.ones((4,3,2,4))
arr

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [18]:
arr.ndim
# np.squeeze(arr)

4

In [22]:
np.squeeze(arr).shape

(2, 4)

In [ ]:
arr.ndim


In [ ]:

arr1 = np.zeros((4,1,3,5,1))
arr1.shape

In [ ]:
np.squeeze(arr1).shape


In [ ]:
arr1.shape

In [ ]:
np.squeeze(arr1,axis = 1).shape

In [23]:
#expanding
arr = np.zeros([4,3,3])

In [24]:
np.expand_dims(arr,axis = 3).shape

(4, 3, 3, 1)

In [25]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Using flatten to create a 1D copy of the array
flattened_arr = arr.flatten()
flattened_arr[0]=3232
print("Original array:")
print(arr)
print("\nFlattened array:")
print(flattened_arr)
print(arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened array:
[3232    2    3    4    5    6    7    8    9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Using ravel to create a 1D view of the array
raveled_arr = arr.ravel()

print("Original array:")
print(arr)
print("\nRaveled array:")
print(raveled_arr)

# Modifying the raveled array and showing it affects the original array
raveled_arr[0] = 10

print("\nModified raveled array:")
print(raveled_arr)
print("\nOriginal array after modifying the raveled array:")
print(arr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Raveled array:
[1 2 3 4 5 6 7 8 9]

Modified raveled array:
[10  2  3  4  5  6  7  8  9]

Original array after modifying the raveled array:
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [28]:
np.linalg.det(arr)

-9.51619735392994e-16

In [29]:
 arr1= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [30]:
np.matmul(arr,arr1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [31]:
arr3 = np.linspace(1,10,50, dtype = 'int16')

In [32]:
arr3

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10],
      dtype=int16)

In [34]:
arr

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [33]:
sliced =arr[0:2,1:4,2:3]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [34]:
sliced

NameError: name 'sliced' is not defined

In [35]:
import numpy as np

# Create a 3D array with shape (3, 4, 5)
arr = np.arange(60).reshape((3, 4, 5))

# Display the original array
print("Original array:")
print(arr)

# Slicing the array
sliced_arr = arr[0:2, 0:4, 2:]

print("\nSliced array:")
print(sliced_arr)


Original array:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

Sliced array:
[[[ 2  3  4]
  [ 7  8  9]
  [12 13 14]
  [17 18 19]]

 [[22 23 24]
  [27 28 29]
  [32 33 34]
  [37 38 39]]]


In [36]:
arr = np.random.rand(2,2,3)

In [37]:
arr

array([[[0.1056474 , 0.9083093 , 0.81002288],
        [0.30944645, 0.9708992 , 0.02456174]],

       [[0.18012546, 0.60785775, 0.83151668],
        [0.32225127, 0.9646898 , 0.83346662]]])

In [38]:
arr = np.random.randint(1,441 , size= (2,4))

In [39]:
arr

array([[331,   6,  84, 355],
       [365, 406,  25, 372]])

In [71]:
arr1 = np.zeros([2,2,4]) 

arr1

In [72]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [73]:
arr = np.ones([3,3,3])

In [74]:
arr

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
arr = np.empty([2,2])

In [76]:
arr

array([[0., 0.],
       [0., 0.]])

In [80]:
arr = np.full((2,3,4),99)

In [81]:
arr

array([[[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]],

       [[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]]])

In [89]:
arr2 = arr.repeat(99, axis = 2)

In [90]:
arr2

array([[[99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99]],

       [[99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99]]])

In [91]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [92]:
arr2

array([[[99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99]],

       [[99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99],
        [99, 99, 99, ..., 99, 99, 99]]])

In [93]:
arr

array([[[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]],

       [[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]]])

In [96]:
arr = np.arange(1,10,.05)

In [97]:
arr

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05,
       2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 ,
       2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  , 3.05, 3.1 , 3.15,
       3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 , 3.55, 3.6 , 3.65, 3.7 ,
       3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25,
       4.3 , 4.35, 4.4 , 4.45, 4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 ,
       4.85, 4.9 , 4.95, 5.  , 5.05, 5.1 , 5.15, 5.2 , 5.25, 5.3 , 5.35,
       5.4 , 5.45, 5.5 , 5.55, 5.6 , 5.65, 5.7 , 5.75, 5.8 , 5.85, 5.9 ,
       5.95, 6.  , 6.05, 6.1 , 6.15, 6.2 , 6.25, 6.3 , 6.35, 6.4 , 6.45,
       6.5 , 6.55, 6.6 , 6.65, 6.7 , 6.75, 6.8 , 6.85, 6.9 , 6.95, 7.  ,
       7.05, 7.1 , 7.15, 7.2 , 7.25, 7.3 , 7.35, 7.4 , 7.45, 7.5 , 7.55,
       7.6 , 7.65, 7.7 , 7.75, 7.8 , 7.85, 7.9 , 7.95, 8.  , 8.05, 8.1 ,
       8.15, 8.2 , 8.25, 8.3 , 8.35, 8.4 , 8.45, 8.

In [99]:
arr[43]

3.150000000000002

In [100]:
arr.mean()

5.475000000000004

In [41]:
arr.std()

160.99534154751186

In [43]:
arr.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [44]:
arr.sum()

1944

In [45]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr2

array([5, 6, 7, 8])

In [47]:
np.dot(arr1,arr2)

ValueError: shapes (3,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

In [48]:
np.matmul(arr1,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [49]:
arr1 = np.arange(1,16).reshape(3,5)

In [50]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [51]:
arr2 = np.arange(10,25).reshape(5,3)

In [52]:
np.dot(arr1,arr2)

array([[ 270,  285,  300],
       [ 670,  710,  750],
       [1070, 1135, 1200]])

In [53]:
np.matmul(arr1,arr2)

array([[ 270,  285,  300],
       [ 670,  710,  750],
       [1070, 1135, 1200]])

In [54]:
np.linalg.det(arr1)

LinAlgError: Last 2 dimensions of the array must be square

In [141]:
arr1 = np.linspace(0,10,8, dtype = float)

In [146]:
arr1

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [55]:
arr1.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [56]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
arr3

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10],
      dtype=int16)

In [58]:
arr3.flatten()

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10],
      dtype=int16)

In [59]:
arr5 = np.arange(1,13).reshape(3,2,2)

In [60]:
arr5.ndim

3

In [61]:
arr5

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [62]:
arr5.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
np.concatenate(arr1,arr5)

TypeError: only integer scalar arrays can be converted to a scalar index

In [66]:
import numpy as np

# Define two arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Concatenate along axis 0 (vertically)
concat_axis_0 = np.concatenate((arr1, arr2), axis=0)

# Concatenate along axis 1 (horizontally)
concat_axis_1 = np.concatenate((arr1, arr2), axis=1)

print("Concatenated along axis 0:")
print(concat_axis_0)

print("\nConcatenated along axis 1:")
print(concat_axis_1)


Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
